services:

  sandbox:
    build: ./sandbox
    container_name: sandbox
    ports:
      - "8000:8000"
    networks:
      - appnet

  streamlit:
    build: ./streamlit-app
    container_name: streamlit
    ports:
      - "8501:8501"
    environment:
      - LLM_API_KEY=${LLM_API_KEY}
    depends_on:
      - sandbox
    volumes:
      - results:/results/autosaves/
    networks:
      - appnet

  server:
    image: projectnumina/kimina-lean-server:2.0.0
    build:
      context: .
    env_file:
      - path: .env
        required: false
    environment:
      - LEAN_SERVER_LEAN_VERSION=v4.26.0

    ports:
      - "80:${LEAN_SERVER_PORT:-8000}"
    restart: unless-stopped
    networks:
      - appnet

networks:
  appnet:
    driver: bridge

volumes:
  results:
    driver_opts:
      type: none
      device: ${PWD}/data/autosaves
      o: bind
